/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import io.github.cdimascio.dotenv.dotenv

fun main() {
    val openaiKey = dotenv()["OPENAI_SECRET_KEY"]

    println("hello your secret key is $openaiKey")
}
